/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.github.pulsebeat02.java-conventions")
}

dependencies {
    providedCompile(project(":MinecraftMediaLibrary"))
    system("org.spigotmc:spigot:1.7.10-R0.1-SNAPSHOT")
}

description = "v1_7_R4"
