/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.github.pulsebeat02.java-conventions")
}

dependencies {
    implementation(project(":v1_16_R3"))
    implementation(project(":v1_16_R2"))
    implementation(project(":v1_16_R1"))
    implementation(project(":v1_15_R1"))
    implementation(project(":v1_14_R1"))
    implementation(project(":v1_13_R2"))
    implementation(project(":v1_13_R1"))
    implementation(project(":v1_12_R1"))
    implementation(project(":v1_11_R1"))
    implementation(project(":v1_10_R1"))
    implementation(project(":v1_9_R2"))
    implementation(project(":v1_9_R1"))
    implementation(project(":v1_8_R3"))
    implementation(project(":v1_8_R2"))
    implementation(project(":v1_8_R1"))
    implementation(project(":v1_7_R4"))
}

description = "MinecraftMediaLibrary-NMS"
