description = "minecraftmedialibrary"

dependencies {

    compileOnlyApi("org.spigotmc:spigot-api:1.16.5-R0.1-SNAPSHOT")
    api("uk.co.caprica:vlcj:4.7.1")
    api("uk.co.caprica:vlcj-natives:4.1.0")
    api("uk.co.caprica:native-streams:1.0.0")
    api("com.github.sealedtx:java-youtube-downloader:2.5.2")
    api("ws.schild:jave-core:3.0.1")
    api("io.netty:netty-all:5.0.0.Alpha2")
    api("com.mojang:authlib:1.5.25")
    api("org.jetbrains:annotations:20.1.0")
    api("org.ow2.asm:asm:9.1")
    api("org.ow2.asm:asm-commons:9.1")
    api("com.github.pulsebeat02:jarchivelib:master-SNAPSHOT")
    api("org.tukaani:xz:1.0")
    api("com.alibaba:fastjson:1.2.73")
    api("net.java.dev.jna:jna:5.8.0")
    api("net.java.dev.jna:jna-platform:5.8.0")
    api("org.bytedeco:javacv-platform:1.5.5")
    api("se.michaelthelin.spotify:spotify-web-api-java:6.5.4")

    testImplementation("org.junit.jupiter:junit-jupiter:5.7.1")
    testImplementation("io.github.glytching:junit-extensions:2.4.0")
    testImplementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.4.31")
    testImplementation("org.jetbrains.kotlin:kotlin-test:1.4.31")

    api(project(":api"))
    api(project(":v1_16_R3"))
    api(project(":v1_16_R2"))
    api(project(":v1_16_R1"))
    api(project(":v1_15_R1"))
    api(project(":v1_14_R1"))
    api(project(":v1_13_R2"))
    api(project(":v1_13_R1"))
    api(project(":v1_12_R1"))
    api(project(":v1_11_R1"))
    api(project(":v1_10_R1"))
    api(project(":v1_9_R2"))
    api(project(":v1_9_R1"))
    api(project(":v1_8_R3"))
    api(project(":v1_8_R2"))
    api(project(":v1_8_R1"))

}