name: DeluxeMediaPlugin
main: com.github.pulsebeat02.deluxemediaplugin.DeluxeMediaPlugin
api-version: 1.16
load: STARTUP
authors: [ PulseBeat_02, BananaPuncher714, Jetp250 ]
version: 1.0.0
description: Play Media in Minecraft